import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import './viewer.css';
const API=import.meta.env.VITE_BACKEND_URL||'http://localhost:8000';
const norm=a=>(a%360+360)%360;
export default function Viewer(){
 const mount=useRef(null),s=useRef({heading:32,pitch:-28,zoom:1,panX:0,panY:0,sync:true});
 const [heading,setHeading]=useState(32),[status,setStatus]=useState('CONNECTING');
 const three=useRef(null); const polar=useRef(null); const grid=useRef(null);
 const publish=()=>{const x=s.current; setHeading(Math.round(norm(x.heading))); try{ws?.send(JSON.stringify({type:'view_state',...x}))}catch{}};
 let ws;
 useEffect(()=>{fetch(`${API}/api/frame`).then(r=>r.json()).then(data=>{setStatus(`BACKEND · ${data.point_count} PTS`); const root=mount.current; if(!root)return;
   const scene=new THREE.Scene(); scene.background=new THREE.Color('#050709'); const cam=new THREE.PerspectiveCamera(44,1,.1,100); cam.position.set(5.2,4.1,6.2);
   const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); root.appendChild(renderer.domElement);
   scene.add(new THREE.HemisphereLight(0x92a9b5,0x101216,2.1)); const light=new THREE.DirectionalLight(0xbfd9ff,2.7);light.position.set(4,7,5);scene.add(light);
   const pos=new Float32Array(data.points.flat()); const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));
   const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:0x9fe9f5,size:.075,sizeAttenuation:true}));scene.add(pts);
   const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(2.3,2.3,2.3)),new THREE.LineBasicMaterial({color:0x1de0ff,transparent:true,opacity:.7}));scene.add(edges);
   const controls=new OrbitControls(cam,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.target.set(0,0,0);three.current={cam,controls};
   const resize=()=>{renderer.setSize(root.clientWidth,root.clientHeight,false);cam.aspect=root.clientWidth/Math.max(1,root.clientHeight);cam.updateProjectionMatrix()};new ResizeObserver(resize).observe(root);resize();
   controls.addEventListener('change',()=>{if(!s.current.sync)return;const o=cam.position.clone().sub(controls.target);s.current.heading=norm(Math.atan2(o.x,o.z)*180/Math.PI);s.current.pitch=Math.asin(Math.max(-1,Math.min(1,o.y/o.length())))*180/Math.PI;s.current.zoom=Math.max(.55,Math.min(1.8,6.7/o.length()));s.current.panX=controls.target.x;s.current.panY=controls.target.z;publish()});
   let id;const loop=()=>{id=requestAnimationFrame(loop);controls.update();renderer.render(scene,cam)};loop();return()=>{cancelAnimationFrame(id);controls.dispose();renderer.dispose();root.innerHTML=''};
 }).catch(()=>setStatus('BACKEND OFFLINE'));
 ws=new WebSocket(API.replace(/^http/,'ws')+'/ws/state');ws.onopen=()=>setStatus('BACKEND · LIVE');ws.onmessage=e=>{const p=JSON.parse(e.data);if(p.type==='state'&&s.current.sync){Object.assign(s.current,p.state);setHeading(Math.round(norm(s.current.heading)))}};return()=>ws?.close()},[]);
 useEffect(()=>{const move=e=>{if(!s.current.sync)return;const g=grid.current,p=polar.current;if(g)g.style.transform=`translate(${s.current.panX*8}px,${-s.current.panY*8}px) rotate(${s.current.heading}deg) scale(${s.current.zoom})`;if(p)p.style.transform=`rotate(${s.current.heading}deg) scale(${s.current.zoom})`};const id=setInterval(move,16);return()=>clearInterval(id)},[]);
 const turn=d=>{s.current.heading=norm(s.current.heading+d);const v=three.current;if(v){const r=v.cam.position.clone().sub(v.controls.target),rad=Math.atan2(r.x,r.z)-d*Math.PI/180,rr=Math.hypot(r.x,r.z);v.cam.position.x=v.controls.target.x+rr*Math.sin(rad);v.cam.position.z=v.controls.target.z+rr*Math.cos(rad);v.controls.update()}publish()};
 return <main className="page"><header className="topbar"><div><h1>Foveated LiDAR Mapping</h1><p>3D model · synchronized 2D · synchronized 2.5D</p></div><div className="header-readout"><span className="dot"/> {status}</div></header>
 <section className="toolbar panel"><div className="pill">3 VIEWS</div><div className="pill muted">360° / 16 RINGS</div><div className="grow"/><button className={s.current.sync?'btn active':'btn'} onClick={()=>{s.current.sync=!s.current.sync;setStatus(s.current.sync?'BACKEND · SYNC ON':'MANUAL')}}><span className="tiny-dot"/>{s.current.sync?'SYNC ON':'SYNC OFF'}</button><button className="btn" onClick={()=>turn(-5)}>↶ 5°</button><button className="btn" onClick={()=>turn(5)}>5° ↷</button></section>
 <section className="views"><article className="view-card"><div className="card-head"><span>3D</span><small>Backend LiDAR point cloud</small></div><div className="three-stage" ref={mount}/><div className="corner axis">X&nbsp; <i>Y</i>&nbsp; Z</div><div className="card-footer">Orbit · Pan · Zoom</div></article>
 <article className="view-card"><div className="card-head"><span>2D</span><small>Backend polar projection</small></div><div className="polar-wrap"><div className="polar-surface" ref={polar}>{Array.from({length:7},(_,i)=><div className="ring" key={i} style={{inset:`${13+i*6}%`}}/>)}{Array.from({length:8},(_,i)=><div className="ray" key={i} style={{transform:`rotate(${i*45}deg)`}}/>)}<div className="center-dot"/><div className="heading-line"/></div><div className="angle-readout">{heading.toString().padStart(3,'0')}°</div></div><div className="card-footer">Azimuth projection</div></article>
 <article className="view-card"><div className="card-head"><span>2.5D</span><small>Backend range grid · 360° ruler</small></div><div className="grid-wrap"><div className="grid-surface" ref={grid}><div className="grid-floor"/>{Array.from({length:9},(_,i)=><div className="scan-row" key={i} style={{top:`${10+i*10}%`}}/>)}{Array.from({length:11},(_,i)=><div className="scan-col" key={i} style={{left:`${5+i*9}%`}}/>)}<div className="fov-ring ring-a"/><div className="fov-ring ring-b"/><div className="fov-ring ring-c"/><div className="object"/><div className="ego"/></div><div className="ruler">{[0,30,60,90,120,150,180,210,240,270,300,330,360].map(d=><span key={d} style={{transform:`rotate(${d}deg) translateY(-102px)`}}>{d}°</span>)}<div className="ruler-pointer" style={{transform:`rotate(${heading}deg)`}}/></div></div><div className="card-footer">Pan · Rotate · Measure 360°</div></article></section>
 <section className="analysis panel"><div><span className="section-kicker">FOV / ORIENTATION</span><strong>{heading}°</strong><small>linked heading</small></div><div><span className="section-kicker">INPUT</span><strong>3D CUBE</strong><small>generated by backend</small></div><div><span className="section-kicker">PIPELINE</span><strong>3D → 2D → 2.5D → FRNet</strong><small>processing boundary is backend</small></div></section></main>}
